## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring.datasource:
  url: jdbc:postgresql://localhost:5432/wagerledger
  username: localuser
  password: localpassword

spring.jpa:
  properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update